VocabularyProject/Models/WordListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VocabularyProject.Data;

namespace VocabularyProject.Models
{
    public class WordListViewModel
    {
        public List<Words> Words{ get; set; }
        public string Key { get; set; }
        

    }
}

VocabularyProject/Controllers/WordController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using VocabularyProject.Data;
using VocabularyProject.Models;

namespace VocabularyProject.Controllers
{
    public class WordController : Controller
    {
        private readonly VocabularyContext _context;

        public WordController(VocabularyContext context)
        {
            _context = context;
        }

        public IActionResult List(string key)
        {
            
            if (key==null)
            {
                key = "";
            }
            var words = from m in _context.Words where m.InEnglish.Contains(key)||m.InAzerbaijan.Contains(key)
                select m;
            string sortType = HttpContext.Request.Query["sortType"];
            if (sortType== "AzerbaijanAtoZ")
            {
                words = words.OrderBy(w => w.InAzerbaijan);
            }
            else if (sortType== "AzerbaijanZtoA")
            {
                words = words.OrderBy(w => w.InAzerbaijan).Reverse();
            }
            else if (sortType== "EnglishAtoZ")
            {
                words = words.OrderBy(w => w.InEnglish);
            }
            else if (sortType== "EnglishZtoA")
            {
                words = words.OrderBy(w => w.InEnglish).Reverse();
            }
            else if (sortType== "date")
            {
                words = words.OrderBy(w => w.AddedTime);
            }
            var model=new WordListViewModel()
            {
                Words = words.ToList()
            };
            return View(model);
            
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> AddWord(Words obj)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    if (obj.Id==0)
                    {
                        obj.AddedTime = DateTime.Now;
                        await _context.Words.AddAsync(obj);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        _context.Entry(obj).State = EntityState.Modified;
                        await _context.SaveChangesAsync();
                    }
                    return RedirectToAction("List");
                }
                return View(obj);
            }
            catch (Exception)
            {
                return RedirectToAction("List");
            }
        }

        public async Task<IActionResult> DeleteWord(int id)
        {
                var word =await  _context.Words.FindAsync(id);
             
                    _context.Words.Remove(word);
                    await _context.SaveChangesAsync();
               return RedirectToAction("List");


        }

      
        
    }
}

VocabularyProject/Views/Shared/_Layout.cshtml
@model WordListViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebUI2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style type="text/css"></style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-primary">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area=""asp-controller="Word" asp-action="List">Home</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Word" asp-action="Create">Add Word</a>

                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input asp-for="Key"  class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button asp-action="List" asp-controller="Word"  class="btn btn-outline-light my-2 my-sm-0" >Search</button>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Select Order
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/word/list?sortType=AzerbaijanAtoZ">Order By Azerbaijan Alphabet A to Z</a>
                            <a class="dropdown-item" href="/word/list?sortType=AzerbaijanZtoA">Order By Azerbaijan Alphabet Z to A</a>
                            <a class="dropdown-item" href="/word/list?sortType=EnglishAtoZ">Order By English Alphabet A to Z</a>
                            <a class="dropdown-item" href="/word/list?sortType=EnglishZtoA">Order By English Alphabet Z to A</a>
                            <a class="dropdown-item" href="/word/list?sortType=date">Order By Date</a>
                        </div>
                    </div>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-primary">
                        @TempData["message"]
                    </div>
                }
            </div>
            <div class="row">
               
                <div class="col">@RenderBody()</div>
            </div>

        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VocabularyProject/Views/Word/Create.cshtml
@model VocabularyProject.Data.Words
<h1>Add Word</h1>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddWord">
            <div class="form-group">
                <label >In Azerbaijan</label><br/>
                @Html.ValidationMessageFor(x=>x.InAzerbaijan," ",new{@class="field-validation-error"})
                @Html.TextBoxFor(x => x.InAzerbaijan )
            </div>
            <div class="form-group">
                <label >In English</label><br/>
                @Html.ValidationMessageFor(x=>x.InEnglish," ",new{@class="field-validation-error"})
                @Html.TextBoxFor(x=>x.InEnglish)
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-success" asp-action="AddWord"/>
            </div>
        </form>
    </div>
</div>


VocabularyProject/Views/Word/List.cshtml
@model WordListViewModel
@{
    ViewData["Title"] = "List";
}
<table class="table">
    <thead>
    <tr>
        <th>
            In Azerbaijan
        </th>
        <th>
            In English
        </th>
        <th>
            Added Time
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Words)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InAzerbaijan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InEnglish)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddedTime)
            </td>
            <td>
               <a href="@Url.Action("DeleteWord",new {item.Id})"class="btn btn-danger">Delete</a>
            </td>

        </tr>
    }
    </tbody>
</table>